### ISSUE TITLE
workflow not triggered on branch

### ISSUE THREAD

**Issue by arauchberger** [ahmadnassri/action-workflow-run-wait#14]
Hi,
everything works as expected on the master-branch.
when i try to do the same on another branch the testing-workflow is never triggered after a successful build-workflow.

i would be happy if you can give me a hint, what i am doing wrong. 
maybe it even has nothing to with your gh-action ;-)

thanks in advance

the build-workflow
```
name: pit-products-ics_1.2.0-nightly

on:
  workflow_dispatch:
  push:
    branches:
      - ics_1.2.0
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '**/.gitignore'
      - '.github/**'
  pull_request:
    branches: [ics_1.2.0]

jobs:
...
``` 

and the test-workflow that should be triggered after the build-workflow
```
name: test-pitaccess-mhs-ics_1.2.0

on:
  workflow_dispatch:
  workflow_run:
    workflows: [pit-products-ics_1.2.0-nightly, pit-products-ics_1.2.0-release]
    branches: [ics_1.2.0]
    types: [completed]

jobs:

  test-pitaccess-mhs:
    name: test-pitaccess-mhs
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    runs-on: ubuntu-latest

    steps:
    
    #########
    # Prerequisites
    #########
      - name: Validate prerequisites
        uses: ahmadnassri/action-workflow-run-wait@v1
...
```
